# Basic
title: MeteorCollector
subtitle: å¯èƒ½æ˜¯ä¸ªäººç«™
description: MeteorCollectorçš„ç”µå­è’åŸ
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: è¿‡è·¯çš„æœ«æŸäºº
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: Computer Science / å¤©æ–‡ / æ¸¸æˆåˆ¶ä½œ
url: "https://meteorcollector.github.io/"

# åšå®¢æ˜¯å¦è‡ªåŠ¨ç”Ÿæˆç›®å½•ï¼Œfalseä¸ºä¸ç”Ÿæˆ
enableToc: true

# Comment
comment:
    livere: MTAyMC81ODAwNy8zNDQ3MA==
    # disqus: leopard
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    # weibo: 5366874726 
    github: MeteorCollector
    # zhihu: panpanleopard
    # juejin: xxx
    # jianshu: 2ada30d8d0f7
    # twitter: 
    # mail: leopardpan@icloud.com


# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: 10294136f424c7c9e549f53673fe6d60  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
# ga:
#    id: UA-84134159-3  
#    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: ä¸‹è½½, description: download, url: '/download'}      
    - {title: å…³äº, description: about, url: '/about'}   
    - {title: live2d, description: iris_model, url: '/iris_model.html'}

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"